package:
  name: {% set name = "robotlab-wheelhouse" %}{{ name }}
  version: {% set version = "1.0rc1" %}{{ version }}

source:
  - url: https://pypi.io/packages/source/r/robotframework-whitelibrary/robotframework-whitelibrary-1.4.0.zip
    sha256: 8247842a2aeb9798182c6eb25a0732851f2b949c63b00e51486f5f92116e1c54
    folder: wheelhouse/robotframework-whitelibrary
  - url: https://pypi.anaconda.org/pythonnet/simple/pythonnet/2.3.0/pythonnet-2.3.0-cp36-cp36m-win_amd64.whl
    sha256: 9fdc77bea92ce04804a7add1bda0450e3931973be1c1719a1279d4764397320b
    folder: wheelhouse

build:
  number: 0
  skip: true  # [unix]
  script:
    - md %PREFIX%\share\wheelhouse
    - xcopy /s /e wheelhouse\* %PREFIX%\share\wheelhouse\
    - cd %PREFIX%\share\wheelhouse
    - Compress-Archive -Path robotframework-whitelibrary -DestinationPath robotframework-whitelibrary-1.4.0.zip
    - dir %PREFIX%\share\wheelhouse

requirements:
  run:
    - pycparser
test:
  commands:
    - dir %PREFIX%\share\wheelhouse
    - python -m pip install --no-index --find-links=%PREFIX%\share\wheelhouse robotframework-whitelibrary pythonnnet
    - python -c "import WhiteLibrary"

about:
  home: https://github.com/robots-from-jupyter/robotlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Offline-installable wheels for RobotLab
  description: |-
    An offline collection of complicated binary wheels. This doesn't actually
    _install_ anything, but does have dependencies.

    Usage:

      python -m pip install --no-index --find-links=%PREFIX%\share\wheelhouse robotframework-whitelibrary pythonnet

    Includes:
    - robotframework-whitelibrary (Apache 2.0)
    - pythonnet (MIT)
