trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr: [master]

variables:
  ROBOTLAB_VERSION: 2020.01.0
  PYTHONUNBUFFERED: 1

jobs:
  # group one: simple conda/webpack builds, validation
  - template: ci/job.noarch.yml
  - template: ci/job.win.yml
  - template: ci/job.lab.yml
  # - template: ci/job.min.yml

  # group two: build installers, verify conda builds
  - template: ci/job.noarch-test.yml
  - template: ci/job.main.yml

  # group three: acceptance testing
  - template: ci/job.selftest.yml

  # group four: reporting, etc
  - template: ci/job.combine.yml
  - template: ci/job.release.yml
