stages:
  - stage: noarch
    jobs:
      - template: ci/job.noarch.yml
        parameters:
          name: Linux
          vmImage: ubuntu-16.04

  - stage: linux
    dependsOn: Noarch
    condition: succeeded()
    jobs:
      - template: ci/job.test.yml
        parameters:
          name: MacOSX
          vmImage: macos-10.13

  - stage: osx
    dependsOn: noarch
    condition: succeeded()
    jobs:
      - template: ci/job.test.yml
        parameters:
          name: MacOSX
          vmImage: macos-10.13

  - stage: windows
    dependsOn: noarch
    condition: succeeded()
    jobs:
      - template: ci/job.test.yml
        parameters:
          name: Windows
          vmImage: vs2017-win2016

  - stage: Combine
    dependsOn:
      - linux
      - osx
      - windows
    condition: always()
    jobs:
    - template: ci/job.combine.yml
      parameters:
        name: Linux
        vmImage: ubuntu-16.04

trigger: [master]

pr: [master]
