jobs:
- template: ci/job.test.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.test.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

- template: ci/job.test.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- template: ci/job.combine.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.deploy.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    githubConnection: robots-from-jupyter
    repositoryName: robots-from-jupyter/robotlab
    artifact: RobotLab

trigger: [master]

pr: [master]
