name: _robots_from_jupyter

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://conda.anaconda.org/conda-forge

dependencies:
  - black
  - conda >=4.7.12,<4.8
  - conda-build >=3.18.9,<3.19
  - conda-verify
  - constructor >=3,<3.1
  - flake8
  - geckodriver
  - python >=3.7,<3.8.0a0
  - python-chromedriver-binary
  - robotframework
  - robotframework-lint
  - robotframework-seleniumlibrary
