name: _robots_from_jupyter

channels:
  - https://conda.anaconda.org/anaconda
  - https://conda.anaconda.org/conda-forge

dependencies:
  - conda >=4.8,<4.9.0a0
  - conda-build >=3.18.9,<3.19
  - conda-verify
  - constructor >=3,<3.1
  - firefox >=68.0.2,<69
  - geckodriver
  - pillow
  - python >=3.6,<3.7.0a0
  - python-libarchive-c
  - ripgrep
  - robotframework
  - robotframework-seleniumlibrary >=4.1.0,<5
