{% set extensions = "@jupyterlab/toc@0.6.0 @jupyter-widgets/jupyterlab-manager@0.38.1" %}
{% set lab_min = "0.35.4" %}
{% set lab_max = "0.36" %}

package:
  name: {% set name = "robotlab" %}{{ name }}
  version: {% set version = "0.9.0" %}{{ version }}

source:
  - path: ../../robotlab
    folder: robotlab
  - url: https://github.com/datakurre/robotkernel/archive/{{ version }}.tar.gz
    sha256: 7e6cabcd7d6ab0760244b5b70093d40e721b7ff9fcddbbdf24dc9ec0ccfb8823
    folder: robotkernel

build:
  number: 0
  entry_points:
    - robotlab = robotlab.labapp:main
    - robotlab-extension = robotlab.labextensionapp:main
    - robotlab-examples = robotlab.examples:copy_robotkernel_examples
  script:
    - cd robotlab
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
    - {{ PYTHON }} -m robotlab.labextensionapp install {{ extensions }} --no-build
    - {{ PYTHON }} -m robotlab.labextensionapp list
    - cd {{ SRC_DIR }}
    - cd robotkernel
    - cd src
    - cd jupyterlab_robotmode
    - jlpm pack .
    - mv *.tgz {{ PREFIX }}/share/jupyter/robotlab/extensions/  # [unix]
    - move *.tgz {{ PREFIX }}\\share\\jupyter\\robotlab\\extensions\\  # [win]
    - {{ PYTHON }} -m robotlab.labextensionapp list
    - {{ PYTHON }} -m robotlab.labapp build
    - rm -rf {{ PREFIX }}/share/jupyter/robotlab/staging  # [unix]
    - rd /s /q {{ PREFIX }}\\share\\jupyter\\robotlab\\staging  # [win]
    - {{ PYTHON }} -m robotlab.labextensionapp list
    - cd {{ SRC_DIR }}
    - cd robotkernel
    - cd examples
    - mkdir -p {{ PREFIX }}/var/www/robotkernel-examples  # [unix]
    - cp *.ipynb {{ PREFIX }}/var/www/robotkernel-examples  # [unix]
    - md {{ PREFIX }}\var\www\robotkernel-examples  # [win]
    - copy *.ipynb {{ PREFIX }}\var\www\robotkernel-examples  # [win]

requirements:
  host:
    - jupyterlab >={{ lab_min }},<{{ lab_max }}
    - nodejs >=8,<9
    - pip
    - python
  run:
    - ipywidgets
    - jupyterlab >={{ lab_min }},<{{ lab_max }}
    - nodejs >=8,<9
    - python
    - robotkernel >={{ version }}

test:
  commands:
    - robotlab --version
    - robotlab-extension list
    - robotlab-examples

about:
  home: https://github.com/datakurre/robotkernel
  license: BSD-3-Clause
  license_family: BSD
  license_file: robotlab/LICENSE
  summary: A JupyterLab built for a robotkernel
