package:
  name: '{% set name = "robotframework-whitelibrary" %}{{ name }}'
  version: '{% set version = "1.6.0" %}{{ version }}'

build:
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
    - pythonnet
  run:
    - robotframework
    - pythonnet
    - python
test:
  imports:
    - WhiteLibrary

about:
  home: https://github.com/Omenia/robotframework-whitelibrary
  license: Apache-2.0
  license_family: Apache
  license_file: apache-2.0.txt
  summary: WhiteLibrary is a Robot Framework library for automating Windows GUI.
  doc_url: http://omenia.github.io/robotframework-whitelibrary/keywords.html
  description: >
    It is a wrapper for TestStack.White automation framework, which is based on
    Microsoft UI Automation API (UIA).
