{% set name = "robotframework-jupyterlibrary" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e36bc75b538d4ccb1fd9a1227e242cf4f49d30df863df4b7e9afc3efaf3e9d76

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - pip
    - python
  run:
    - pillow
    - python
    - robotframework >=3.1
    - robotframework-seleniumlibrary >=3.2.0
    - six

test:
  imports:
    - JupyterLibrary

about:
  home: https://robotframework-jupyterlibrary.rtfd.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for automating (testing of) Jupyter end-user applications and extensions
  dev_url: https://github.com/bollwyvl/robotframework-jupyterlibrary
