package:
  name: '{% set name = "pyshortcuts" %}{{ name }}'
  version: '{% set version = "1.4" %}{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 503820fce779cf42e9b52e4674f5ef0b1672930d662401af53a6a73d07360a8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyshortcut = pyshortcuts:shortcut_cli

requirements:
  host:
    - pip
    - python
  run:
    - six
    - python
    - pywin32  # [win]

test:
  requires:
    - wxpython
  imports:
    - pyshortcuts
    - pyshortcuts.darwin
    - pyshortcuts.linux
    - pyshortcuts.windows
    - pyshortcuts.wxgui

  commands:
    - pyshortcut --help

about:
  home: https://github.com/newville/pyshortcuts
  license: MIT
  license_file: LICENSE
  summary: create desktop shortcuts to python scripts on Windows, Mac, or Linux
