package:
  name: '{% set name = "pythonnet" %}{{ name }}'
  version: '{% set version = "2.3.0" %}{{ version }}'

build:
  skip: True  # [unix]
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 74287603a2e8e791e800f7ee8b7198a3939820ee4a886ad0a6517d2153db306d

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - clr

about:
  home: https://github.com/pythonnet/pythonnet
  license: MIT
  license_family: MIT
  license_file: LICENSE
