jobs:
  - job: lab
    pool:
      vmImage: ubuntu-16.04

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: conda $PATH

      - script: conda env update -n base --file ci/env-lab.yml
        displayName: install minimal lab build environment

      - script: python -m scripts.build lab
        displayName: build lab

      - script: rm -rf _artifacts/app_dir/staging
        displayName: clean lab cruft

      - task: PublishPipelineArtifact@0
        displayName: publish jupyterlab package
        inputs:
          targetPath: _artifacts/app_dir
          artifactName: robotlab app_dir
        condition: succeeded()
