parameters:
  name: Linux
  vmImage: ubuntu-16.04
  githubConnection: release-robots-from-jupyter
  repositoryName: robots-from-jupyter/robotlab
  platforms:
    - Linux
    - MacOSX
    - Windows
  products:
    - MiniRobot
    - ExoRobot
    - RobotLab
  artifact: RobotLab
  constructors: _artifacts/constructor

jobs:
  - job: Combine
    dependsOn:
      - ${{ each platform in parameters.platforms }}:
        - ${{ each product in parameters.products }}:
          - ${{ product }}${{ platform }}Test
    condition: always()
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: steps.conda.yml
        parameters:
          envPath: ci/env-combine.yml

      - ${{ each platform in parameters.platforms }}:
        - ${{ each product in parameters.products }}:
          - task: DownloadPipelineArtifact@0
            condition: always()
            inputs:
              artifactName: ${{ product }} ${{ platform }} Output
              targetPath: _artifacts/test_output
            displayName: Restore ${{ product }} ${{ platform }} Output

      - script: python -m scripts.combine
        condition: always()
        displayName: Rebot

      - task: PublishPipelineArtifact@1
        condition: always()
        displayName: Publish Combined Robot Output
        inputs:
          targetPath: _artifacts/test_output
          artifactName: Robot Output
