parameters:
  name: Linux
  vmImage: ubuntu-16.04
  githubConnection: release-robots-from-jupyter
  repositoryName: robots-from-jupyter/robotlab
  platforms:
    - Linux
    - MacOSX
    - Windows
  artifact: RobotLab
  constructors: _artifacts/constructor

jobs:
  - job: Deploy
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn:
      - ${{ each platform in parameters.platforms }}:
        - ${{ platform }}Test
      - conda_win_test
      - conda_noarch_test
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    steps:
      - ${{ each platform in parameters.platforms }}:
        - task: DownloadPipelineArtifact@0
          displayName: Fetch ${{ platform }} Installer
          inputs:
            artifactName: ${{ parameters.artifact }} For ${{ platform }}
            targetPath: ${{ parameters.constructors }}
      - script: find .
        displayName: list files before release
      - script: cd ${{ parameters.constructors }} && sha256sum * >> SHA256SUMS
        displayName: build hashes
      - task: GithubRelease@0
        inputs:
          githubConnection: ${{ parameters.githubConnection }}
          repositoryName: ${{ parameters.repositoryName }}
          assets: ${{ parameters.constructors }}/*
          isDraft: true
