jobs:
  - job: noarch
    pool:
      vmImage: ubuntu-16.04

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: conda $PATH

      - script: conda env update -n base --file ci/env-noarch.yml
        displayName: install minimal build/qa environment

      - script: python -m scripts.integrity
        displayName: check integrity

      - script: python -m scripts.integrity
        displayName: lint

      - script: |-
          python -m scripts.build conda \
            restinstance \
            robotframework-jupyterlibrary \
            robotframework-seleniumscreenshots \
            robotkernel
        displayName: build noarch packages

      - task: PublishPipelineArtifact@0
        displayName: publish noarch packags
        inputs:
          targetPath: _artifacts/conda-bld/noarch
          artifactName: Noarch Conda Packages
        condition: succeeded()
