parameters:
  platforms:
  - name: Linux
    vmImage: ubuntu-16.04
    activate: ""
  - name: MacOSX
    vmImage: macos-10.13
    activate: ""
  - name: Windows
    vmImage: vs2017-win2016
    activate: call activate &&

jobs:
  - ${{ each platform in parameters.platforms }}:
    - job: CondaNoarchTest${{ platform.name }}
      pool:
        vmImage: ${{ platform.vmImage }}
      condition: succeeded()
      dependsOn:
        - CondaNoarch
        - CondaWindows

      steps:
        - template: steps.restore.yml
          parameters:
            name: ${{ platform.name }}

        - template: steps.conda.yml
          parameters:
            name: ${{ platform.name }}

        - script: ${{ platform.activate }} python -m scripts.test conda
          displayName: test prebuilt packages
