parameters:
  name: Linux
  vmImage: ubuntu-16.04
  product: RobotLab

jobs:
  - job: ${{ parameters.product }}${{ parameters.name }}Test
    condition: succeeded()
    dependsOn:
      - ${{ parameters.product }}${{ parameters.name }}Build
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: ${{ parameters.product }} for ${{ parameters.name }}
          targetPath: _artifacts/constructor
        displayName: restore installer

      - ${{ if not(eq(parameters.name, 'Windows')) }}:
        - script: bash _artifacts/constructor/${{ parameters.product }}-$(ROBOTLAB_VERSION)-${{ parameters.name }}-x86_64.sh -fbp _${{ parameters.product }}
          displayName: run installer
        - script: . ./_${{ parameters.product }}/bin/activate ./_${{ parameters.product }} && python -m scripts.test robot ${{ parameters.product }} --headless --in-product
          displayName: acceptance tests

      - ${{ if eq(parameters.name, 'Windows') }}:
        - script: |
            @echo on
            echo %HOME%
            md "%cd%\_${{ parameters.product }}"
            start /wait "" "_artifacts\constructor\${{ parameters.product }}-$(ROBOTLAB_VERSION)-Windows-x86_64.exe" /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /S /D=%cd%\_${{ parameters.product }}
          displayName: run installer
        - script: |
            @echo on
            call "%cd%\_${{ parameters.product }}\Scripts\activate.bat" "%cd%\_${{ parameters.product }}"
            python -m scripts.test robot --headless --in-product ${{ parameters.product }}
          displayName: acceptance tests

      - ${{ if eq(parameters.name, 'MacOSX') }}:
        - script: chmod -R 777 _artifacts
          displayName: fix artifact permissions

      - task: PublishTestResults@2
        displayName: publish test results
        inputs:
          testResultsFiles: _artifacts/test_output/**/*.xunit.xml
        condition: always()

      - task: PublishPipelineArtifact@0
        displayName: publish robot output
        inputs:
          targetPath: _artifacts/test_output
          artifactName: ${{ parameters.product }} ${{ parameters.name }} Output
        condition: always()
