parameters:
  githubConnection: release-robots-from-jupyter
  repositoryName: robots-from-jupyter/robotlab
  platforms:
    - Linux
    - MacOSX
    - Windows
  products:
    - MiniRobot
    - ExoRobot
    - RobotLab
  constructors: _artifacts/constructor

jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-16.04
    dependsOn:
      - ${{ each platform in parameters.platforms }}:
        - CondaNoarchTest${{ platform.name }}
        - ${{ each product in parameters.products }}:
          - ${{ product }}${{ platform }}Test
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    steps:
      - ${{ each product in parameters.products }}:
        - ${{ each platform in parameters.platforms }}:
          - task: DownloadPipelineArtifact@0
            displayName: fetch ${{ product }} ${{ platform }} Installer
            inputs:
              artifactName: ${{ product }} For ${{ platform }}
              targetPath: ${{ parameters.constructors }}
      - script: find .
        displayName: list files before release
      - script: cd ${{ parameters.constructors }} && sha256sum * >> SHA256SUMS
        displayName: build hashes
      - task: GithubRelease@0
        inputs:
          githubConnection: ${{ parameters.githubConnection }}
          repositoryName: ${{ parameters.repositoryName }}
          assets: ${{ parameters.constructors }}/*
          isDraft: true
