jobs:
  - job: qa
    pool:
      vmImage: ubuntu-16.04

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: conda $PATH

      - script: conda env update -n base --file ci/env-qa.yml
        displayName: install minimal qa environment

      - script: python -m scripts.integrity
        displayName: check integrity

      - script: python -m scripts.lint
        displayName: lint
