jobs:
  - job: CondaNoarch
    pool:
      vmImage: ubuntu-16.04

    steps:
      - template: steps.conda.yml

      - script: |-
          python -m scripts.build conda \
            --no-test \
            robotframework \
            restinstance \
            robotframework-jupyterlibrary \
            robotframework-seleniumscreenshots \
            robotkernel \
            robotframework-ride
        displayName: build noarch packages

      - task: PublishPipelineArtifact@0
        displayName: publish noarch packages
        inputs:
          targetPath: _artifacts/conda-bld/noarch
          artifactName: noarch conda packages $(Build.BuildId)
        condition: succeeded()
