jobs:
  - job: conda noarch
    pool:
      vmImage: ubuntu-16.04

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: conda $PATH

      - script: conda env update -n base --file ci/env-noarch.yml
        displayName: install minimal build environment

      - script: |-
          python -m scripts.build conda \
            restinstance \
            robotframework-jupyterlibrary \
            robotframework-seleniumscreenshots \
            robotkernel
        displayName: build noarch packages

      - task: PublishPipelineArtifact@0
        displayName: publish noarch packages
        inputs:
          targetPath: _artifacts/conda-bld/noarch
          artifactName: noarch conda packages
        condition: succeeded()
